10.129.6.52 - - [09/Feb/2020 11:47:43] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 11:47:43] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 11:47:46] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 11:47:46] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 11:47:46] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 11:47:46] "GET /setup.in HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 606, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
10.129.6.52 - - [09/Feb/2020 11:53:24] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 11:53:24] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 11:53:28] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 11:53:28] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 11:53:28] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 11:53:28] "GET /setup.in HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 606, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
10.129.6.52 - - [09/Feb/2020 11:55:14] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 11:55:15] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 11:55:18] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 11:55:18] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 11:55:18] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 11:55:18] "GET /setup.in HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 606, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
10.129.6.52 - - [09/Feb/2020 12:09:18] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:09:18] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:09:21] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:09:21] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:09:21] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:09:21] "GET /setup.in HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 606, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
10.129.6.52 - - [09/Feb/2020 12:12:11] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:12:11] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:12:14] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:12:14] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:12:14] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:12:14] "GET /setup.in HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 606, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
10.129.6.52 - - [09/Feb/2020 12:22:54] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:22:54] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:22:58] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:22:58] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:22:58] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:22:58] "GET /setup.in HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 606, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
10.129.6.52 - - [09/Feb/2020 12:25:54] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:25:54] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:25:57] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:25:58] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:25:58] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:25:58] "GET /setup.in HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 606, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
10.129.6.52 - - [09/Feb/2020 12:29:21] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:29:21] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:29:25] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:29:26] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:29:26] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:29:26] "GET /setup.in HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 606, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
10.129.6.52 - - [09/Feb/2020 12:31:35] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:31:35] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:31:39] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:31:39] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:31:39] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:31:39] "GET /setup.in HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 606, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
10.129.6.52 - - [09/Feb/2020 12:39:37] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:39:37] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:39:41] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:39:41] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:39:41] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:39:41] "GET /setup.in HTTP/1.1" 200 -
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 235, in <module>
    test()
  File "/usr/lib/python2.7/SimpleHTTPServer.py", line 231, in test
    BaseHTTPServer.test(HandlerClass, ServerClass)
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 606, in test
    httpd = ServerClass(server_address, HandlerClass)
  File "/usr/lib/python2.7/SocketServer.py", line 417, in __init__
    self.server_bind()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 108, in server_bind
    SocketServer.TCPServer.server_bind(self)
  File "/usr/lib/python2.7/SocketServer.py", line 431, in server_bind
    self.socket.bind(self.server_address)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 98] Address already in use
10.129.6.52 - - [09/Feb/2020 12:42:56] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:42:56] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:43:00] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:43:00] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:43:00] "GET /setup.in HTTP/1.1" 200 -
10.129.6.52 - - [09/Feb/2020 12:43:00] "GET /setup.in HTTP/1.1" 200 -
